### PR TITLE
Upgrade gir dependencies to x.x.x-4.0.0-beta.3

### PR DESCRIPTION
**Pull request by Totto16**

### CODE REVIEW

**Comment by swsnr** [comment]
beta.3?  I see that's a publish version but where does it come from?  I'm not seeing a corresponding tag in ts-for-gir, and didn't find the changes in the types repo 🤔

**Comment by Totto16** [comment]
It's from [here](https://github.com/gjsify/types/tree/next) , it's ion a separate branch

**Comment by JumpLink** [comment]
I am currently working on this PR: https://github.com/gjsify/ts-for-gir/pull/162

The PR is almost finished but I'm still waiting for a review, but I've already released the next beta anyway

**Review by swsnr — APPROVED** [review]
Feel free to merge.

**Comment by Totto16** [comment]
I think it would be better, if I'd wait for https://github.com/gjsify/ts-for-gir/pull/162 and if that gets merged without new changes I'll merge it right away, otherwise I bump these versiosn again

**Comment by Totto16** [comment]
Since https://github.com/gjsify/ts-for-gir/pull/162 might take a while, I'll merge this nonetheless before it's been merged, so that I can make a new release with #36 #37 and #38

**Pull request merged**
