### PR TITLE
Recheck and Improve some types

### PR DESCRIPTION
**Pull request by Totto16**
Recheck many types and improve them:
- add signal types, where possible
- fix inconsistencies in the way, constructor parameters where declared
- add links where necessary or add more `@version 46` specifier

### CODE REVIEW

**Comment by Totto16** [comment]
I have a question regarding [this](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/panelMenu.js#L95)

how to implement this in the cleanest way:

```js

export const Button = GObject.registerClass({
    Signals: {'menu-set': {}},
}, class PanelMenuButton extends ButtonBox [
...
}


```


We can't extend multiple classes, otherwise I would have done this:
```ts


export class Button extends ButtonBox,Signals.EventEmitter<Button.SignalMap> {
}

```

See [here](https://github.com/gjsify/gnome-shell/blob/8f2e11e9178be6713597c53bd1d54e236dede131/packages/gnome-shell/src/ui/panelMenu.d.ts#L51)


I saw some TODO's around the place, like e.g. [here](https://github.com/gjsify/gnome-shell/blob/main/packages/gnome-shell/src/ui/appDisplay.d.ts#L23)

So is this not possible easily, (so only by duplicating the signals types inside the class ?)

**Comment by swsnr** [comment]
I believe that TODO is wrong.  `Signals.EventEmitter` is not just a utility we defined here; it's actually a separate independent class defined by GNOME Shell. 

`Button` does not inherit from `EventEmitter`, so these types shouldn't pretend it does, in my opinion.

To declare signal types in gobject-derived classes, you'd instead declare specific overloads for `connect`, see e.g. [`PopupMenu.Switch`](https://github.com/gjsify/gnome-shell/blob/43196befe6f07329d7e87f0d217895abae652e70/packages/gnome-shell/src/ui/popupMenu.d.ts#L110)

**Review by swsnr — APPROVED** [review]
Looks good. Thanks for adding links to the sources :+1: :pray:

**Comment by Totto16** [comment]
> I believe that TODO is wrong. `Signals.EventEmitter` is not just a utility we defined here; it's actually a separate independent class defined by GNOME Shell.
> 
> `Button` does not inherit from `EventEmitter`, so these types shouldn't pretend it does, in my opinion.
> 
> To declare signal types in gobject-derived classes, you'd instead declare specific overloads for `connect`, see e.g. [`PopupMenu.Switch`](https://github.com/gjsify/gnome-shell/blob/43196befe6f07329d7e87f0d217895abae652e70/packages/gnome-shell/src/ui/popupMenu.d.ts#L110)

That seem legit, thanks, I didn't deep dive into this topic, as I don't use those signals in my project, but for completeness I'll wanted to add this type, 👍🏼

**Comment by Totto16** [comment]
This is now everything, I wanted to check, I added some minor fixes / types and some more signal types.

It would be a good idea, to make a new beta release, since #32 and this are quite a few additions to test, and    https://github.com/gjsify/ts-for-gir/issues/149

**Review by swsnr — APPROVED** [review]

**Pull request merged**
