### PR TITLE
Bump beta @girs dependencies 

### PR DESCRIPTION
**Pull request by Totto16**
The previous bump bumped all versions to `x.x.x-4.0.0-beta.3` but some dependencies received another update, presumably to fix some things.

This are to my current knowledge: 
- `@girs/gtk-4.0` from `4.14.1-4.0.0-beta.3` to `4.14.2-4.0.0-beta.3`
- `@girs/pango-1.0` from `1.51.0-4.0.0-beta.3` to `1.52.2-4.0.0-beta.3`

We only use some of those directly, so I bumped them:

- bump @girs/gtk-4.0 to the newest beta version (`4.14.2-4.0.0-beta.3`)

This doesn't work atm because of some discrepancies in the sub-dependencies, which use different versions.

Edit: the bump from  `@girs/pango-1.0` from `1.51.0-4.0.0-beta.3` to `1.52.2-4.0.0-beta.3` seems to be a minor version chnage, this could be omitted, since I don't know if pango-1.52 is shipped with gnome-36 or maybe only in gnome-47

### CODE REVIEW

**Comment by Totto16** [comment]
@JumpLink would it be possible, to release a new version of the dependencies, which use the old versions of those two dependencies ?:

- `@girs/gtk-4.0` from `4.14.1-4.0.0-beta.3` 
- `@girs/pango-1.0` from `1.51.0-4.0.0-beta.3` 


As far as I see, these would be:

- `@girs/adw-1@1.5.0-4.0.0-beta.3` uses `@girs/gtk-4.0@4.14.1-4.0.0-beta.3`
- `@girs/shew-0@0.0.0-4.0.0-beta.3` uses `@girs/gtk-4.0@4.14.1-4.0.0-beta.3`

`@girs/pango-1.0@1.51.0-4.0.0-beta.3`

is used by 13 other `@girs` packages, just replace the occurrences of these, Im not listing those here 😓

**Comment by JumpLink** [comment]
@Totto16 I have now released new types in version `4.0.0-beta.5`, these should now all use the latest version, including each other, can you confirm this and does this fix the problem?

**Comment by Totto16** [comment]
> @Totto16 I have now released new types in version `4.0.0-beta.5`, these should now all use the latest version, including each other, can you confirm this and does this fix the problem?

Yes, that fixes it, thanks ❤️

**Comment by JumpLink** [comment]
@Totto16 Just in case you don't know, with `yarn upgrade-interactive` you can update all dependencies very easily

**Comment by Totto16** [comment]
> @Totto16 Just in case you don't know, with `yarn upgrade-interactive` you can update all dependencies very easily

Oh thanks, I really didn't know that, I always used npm / pnpm and have a cool VSCode tool, so that I can update them manually 😓 . Thanks ❤️

**Pull request merged**
