### PR TITLE
Add types for rounded-window-corners

### PR DESCRIPTION
**Pull request by flexagoon**
Add extra types required for the https://github.com/flexagoon/rounded-window-corners extension

### CODE REVIEW

**Review by swsnr — CHANGES_REQUESTED** [review]
Please add a `@version 46` annotation comment to all exported classes; this helps us keep track of things across Gnome major upgrades.

Take a look at the code to see how these comments should look like.

**Comment by swsnr** [comment]
@flexagoon CI complains about formatting; you'll need to run prettier on the code.

**Comment by flexagoon** [comment]
Oh, formatting is failing because they got formatted by the typescript lsp

Sure, I'll run prettier on my changes

**Comment by flexagoon** [comment]
@swsnr ok, the formatting should be fixed now

**Review by Totto16 — APPROVED** [review]

**Comment by Totto16** [comment]
Seems good, thank you for your configuration ❤️

**Comment by flexagoon** [comment]
@Totto16 how often does this library get new releases? When will I be able to use the contributed types?

**Comment by Totto16** [comment]
> @Totto16 how often does this library get new releases? When will I be able to use the contributed types?

That depends on the amount of commits, we usually don't make releases with just 1-2 commits / changes.

But I am working on some things today, so likely today.

And if I wasn't we / I could just make a release, that would be possible too, but we try to batch them together.

Feel free to subscribe to releases in this repo, as we always make a GitHub (Pre)-release too, so you get a notification ❤️

**Pull request merged**
