### PR TITLE
Port some types to GNOME 46

### PR DESCRIPTION
**Pull request by swsnr**
See #21

### CODE REVIEW

**Comment by swsnr** [comment]
I've started to go through my extensions; this is from the simpler ones.  The more complex ones are still to come, and I expect that this PR will take a few days to complete.  Opened a draft anyway to collect feedback as I go.

I've added a `GNOME 46` comment to every type I've check to help me keep track of things.  I can remove those comments are this is finished again, but perhaps it's helpful to track which types are GNOME 46 already?  Perhaps it could be formalized to some degree?

**Comment by JumpLink** [comment]
@swsnr If you change the GNOME 46 comments to `/** @version 46 */`, you are welcome to leave them in 👍
Preferably with further information if you know it.

**Comment by swsnr** [comment]
@JumpLink I've changed the annotations to your style.

Not sure though, what you mean with "further" information… my idea was just to mark every type which has been scrutinized for GNOME 46, to keep track of things, and inform other people looking at this that they perhaps don't need to look at these types again.  What further information should I provide?

**Comment by swsnr** [comment]
Wrt to https://github.com/gjsify/gnome-shell/pull/23#issuecomment-2023430895 I've marked this as ready, because what's been corrected here can essentially already be merged as is 🙂 

I'll try to make separate MRs for more complex changes.

**Comment by JumpLink** [comment]
> @JumpLink I've changed the annotations to your style.
> 
> Not sure though, what you mean with "further" information… my idea was just to mark every type which has been scrutinized for GNOME 46, to keep track of things, and inform other people looking at this that they perhaps don't need to look at these types again. What further information should I provide?

For example if there are comments in the original javascript source file then these can be adopted.

**Pull request merged**
